### ISSUE TITLE
Clarity on Maze2D/AntMaze

### ISSUE THREAD

**Issue by AlexBeesonWarwick** [Farama-Foundation/D4RL#142]
Hi

Thank you very much for providing and maintaining these datasets; they are an important benchmarking resource for offline-RL.

I have a query about the Maze2D/AntMaze environments.  It basically boils down to, is this a single-goal or multi-goal task?

It seems that when training agents using these datasets, we are only inputting the state and not the state+goal.  I note that when calling env.reset() the goal doesn't change, or only changes a tiny bit (e.g. for Large it is always top right).  Is the task therefore to train agents to reach this one goal using trajectories in the dataset that have many goals, i.e. it is not a multi-goal task?  Surely if it was multi-goal (i.e. changing goal) we'd need to input both state and goal.

Anecdotally, I've found that including the goal as an input can greatly improve the performance of algorithms like TD3-BC on the harder tasks like antmaze-large-diverse-v2.  But this seems like a really obvious thing to do, and makes me wonder if I'm not understanding what the tasks actually is.

I'd be grateful for some clarity please.

Many thanks

**Comment by odelalleau** [comment]
I agree this does not really make sense. What's even more confusing is this long comment here:
https://github.com/Farama-Foundation/D4RL/blob/4235ef21ac5ba35285ecfce133d9eff62f3490e5/d4rl/locomotion/ant.py#L189

It explains how important it is to randomize the goal at evaluation, but then what actually happens in practice is that because the maze has a fixed goal cell (I'm taking `antmaze-medium-play-v2` as an example), the only randomization that occurs is the minor noise added at:
https://github.com/Farama-Foundation/D4RL/blob/4235ef21ac5ba35285ecfce133d9eff62f3490e5/d4rl/locomotion/maze_env.py#L253

So in the end we really only evaluate on one goal, while the dataset uses randomized goals that are not provided to the agent. This doesn't really look like a reasonable way to benchmark offline RL algorithms.

**Comment by rodrigodelazcano** [comment]
Hi! We are refactoring the AntMaze and PointMaze in the [Gymnasium-Robotics](https://github.com/Farama-Foundation/Gymnasium-Robotics/pull/42) repo. This will include environments with single goal, multi-goal, and custom goals at reset time.

We are also planning to regenerate the offline datasets with the refactor environments in a new offline API called [Kabuki](https://github.com/Farama-Foundation/Kabuki)

**Comment by odelalleau** [comment]
Thanks @rodrigodelazcano, that sounds great!
