### ISSUE TITLE
[Question] How can I collect expert demonstrations for modified environments

### ISSUE THREAD

**Issue by arcosin** [Farama-Foundation/D4RL#209]
Hello,

I would like to modify one of the maze environments and collect new expert trajectories.
It is my understanding that you use RL algorithms to learn, then sample the trajectories from them.
Do you have a specific implementation for this? Or a set way to collect new demonstrations?
If not, what implementation did you use?

Thank you!

**Comment by rodrigodelazcano** [comment]
We are moving all of the datasets to a new library under Farama called [Minari](https://github.com/Farama-Foundation/Minari). It also supports data collection utilities to create new datasets. There is also a tutorial available for data collection of the point maze environment https://minari.farama.org/main/tutorials/dataset_creation/point_maze_dataset/.

Note that you'll have to install Minari from source since we are expecting to make a beta release soon.

**Comment by arcosin** [comment]
Interesting. Thanks!
